[2023-12-10T18:12:29.674+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KOH.data_tts manual__2023-12-10T13:11:58.517393+00:00 [queued]>
[2023-12-10T18:12:29.690+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KOH.data_tts manual__2023-12-10T13:11:58.517393+00:00 [queued]>
[2023-12-10T18:12:29.692+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-10T18:12:29.764+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_tts> on 2023-12-10 13:11:58.517393+00:00
[2023-12-10T18:12:29.769+0500] {standard_task_runner.py:57} INFO - Started process 5686 to run task
[2023-12-10T18:12:29.790+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'KOH', 'data_tts', 'manual__2023-12-10T13:11:58.517393+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/text.py', '--cfg-path', '/tmp/tmp3etdwfay']
[2023-12-10T18:12:29.798+0500] {standard_task_runner.py:85} INFO - Job 23: Subtask data_tts
[2023-12-10T18:12:29.899+0500] {task_command.py:416} INFO - Running <TaskInstance: KOH.data_tts manual__2023-12-10T13:11:58.517393+00:00 [running]> on host vm2.myguest.virtualbox.org
[2023-12-10T18:12:30.096+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='KOH' AIRFLOW_CTX_TASK_ID='data_tts' AIRFLOW_CTX_EXECUTION_DATE='2023-12-10T13:11:58.517393+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-10T13:11:58.517393+00:00'
[2023-12-10T18:12:30.097+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-10T18:12:30.098+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd home/kda/ML_lab3/MLops_lab3/ && python home/kda/ML_lab3/MLops_lab3/scripts/train_test_split.py']
[2023-12-10T18:12:30.114+0500] {subprocess.py:86} INFO - Output:
[2023-12-10T18:12:30.115+0500] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: home/kda/ML_lab3/MLops_lab3/: No such file or directory
[2023-12-10T18:12:30.115+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-10T18:12:30.122+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-10T18:12:30.125+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=KOH, task_id=data_tts, execution_date=20231210T131158, start_date=20231210T131229, end_date=20231210T131230
[2023-12-10T18:12:30.159+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task data_tts (Bash command failed. The command returned a non-zero exit code 1.; 5686)
[2023-12-10T18:12:30.175+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-10T18:12:30.206+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
