[2023-12-26T23:37:14.103+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KOH.evaluate manual__2023-12-26T18:30:46.214702+00:00 [queued]>
[2023-12-26T23:37:14.127+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KOH.evaluate manual__2023-12-26T18:30:46.214702+00:00 [queued]>
[2023-12-26T23:37:14.128+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-26T23:37:14.218+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): evaluate> on 2023-12-26 18:30:46.214702+00:00
[2023-12-26T23:37:14.232+0500] {standard_task_runner.py:57} INFO - Started process 12892 to run task
[2023-12-26T23:37:14.238+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'KOH', 'evaluate', 'manual__2023-12-26T18:30:46.214702+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/text.py', '--cfg-path', '/tmp/tmpccimvs93']
[2023-12-26T23:37:14.240+0500] {standard_task_runner.py:85} INFO - Job 122: Subtask evaluate
[2023-12-26T23:37:14.392+0500] {task_command.py:416} INFO - Running <TaskInstance: KOH.evaluate manual__2023-12-26T18:30:46.214702+00:00 [running]> on host vm2.myguest.virtualbox.org
[2023-12-26T23:37:14.572+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='KOH' AIRFLOW_CTX_TASK_ID='evaluate' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T18:30:46.214702+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T18:30:46.214702+00:00'
[2023-12-26T23:37:14.574+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-26T23:37:14.577+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/kda/ML_lab3/MLops_lab3/ && python /home/kda/ML_lab3/MLops_lab3/scripts/evaluate.py']
[2023-12-26T23:37:14.611+0500] {subprocess.py:86} INFO - Output:
[2023-12-26T23:37:20.196+0500] {subprocess.py:93} INFO -      Price (in USD)  Unnamed: 0.2  Unnamed: 0.1  ...  Z4 M40i  Z4 Roadster     i8
[2023-12-26T23:37:20.196+0500] {subprocess.py:93} INFO - 0             67600           912           912  ...    False        False  False
[2023-12-26T23:37:20.196+0500] {subprocess.py:93} INFO - 1             81250           843           843  ...    False        False  False
[2023-12-26T23:37:20.196+0500] {subprocess.py:93} INFO - 2             69000           293           293  ...    False        False  False
[2023-12-26T23:37:20.196+0500] {subprocess.py:93} INFO - 3            180000           554           554  ...    False        False  False
[2023-12-26T23:37:20.197+0500] {subprocess.py:93} INFO - 4             64695           581           581  ...    False        False  False
[2023-12-26T23:37:20.197+0500] {subprocess.py:93} INFO - ..              ...           ...           ...  ...      ...          ...    ...
[2023-12-26T23:37:20.197+0500] {subprocess.py:93} INFO - 298          250000           951           951  ...    False        False  False
[2023-12-26T23:37:20.197+0500] {subprocess.py:93} INFO - 299         2600000           523           523  ...    False        False  False
[2023-12-26T23:37:20.197+0500] {subprocess.py:93} INFO - 300          103500            61            61  ...    False        False  False
[2023-12-26T23:37:20.197+0500] {subprocess.py:93} INFO - 301          157500           355           355  ...    False        False  False
[2023-12-26T23:37:20.197+0500] {subprocess.py:93} INFO - 302          200000           335           335  ...    False        False  False
[2023-12-26T23:37:20.197+0500] {subprocess.py:93} INFO - 
[2023-12-26T23:37:20.198+0500] {subprocess.py:93} INFO - [303 rows x 220 columns]
[2023-12-26T23:37:20.199+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-26T23:37:20.199+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/scripts/evaluate.py", line 32, in <module>
[2023-12-26T23:37:20.199+0500] {subprocess.py:93} INFO -     with open(input_model,"rb") as ff:
[2023-12-26T23:37:20.199+0500] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/kda/ML_lab3/MLops_lab3/models/model.pkl'
[2023-12-26T23:37:20.600+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-26T23:37:20.607+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-26T23:37:20.609+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=KOH, task_id=evaluate, execution_date=20231226T183046, start_date=20231226T183714, end_date=20231226T183720
[2023-12-26T23:37:20.664+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 122 for task evaluate (Bash command failed. The command returned a non-zero exit code 1.; 12892)
[2023-12-26T23:37:20.705+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-26T23:37:20.727+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
