[2023-12-26T22:56:00.209+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KOH.data_ml manual__2023-12-26T17:55:20.000429+00:00 [queued]>
[2023-12-26T22:56:00.220+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KOH.data_ml manual__2023-12-26T17:55:20.000429+00:00 [queued]>
[2023-12-26T22:56:00.221+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-26T22:56:00.274+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_ml> on 2023-12-26 17:55:20.000429+00:00
[2023-12-26T22:56:00.280+0500] {standard_task_runner.py:57} INFO - Started process 11595 to run task
[2023-12-26T22:56:00.289+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'KOH', 'data_ml', 'manual__2023-12-26T17:55:20.000429+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/text.py', '--cfg-path', '/tmp/tmpl_slhh6i']
[2023-12-26T22:56:00.291+0500] {standard_task_runner.py:85} INFO - Job 63: Subtask data_ml
[2023-12-26T22:56:00.430+0500] {task_command.py:416} INFO - Running <TaskInstance: KOH.data_ml manual__2023-12-26T17:55:20.000429+00:00 [running]> on host vm2.myguest.virtualbox.org
[2023-12-26T22:56:00.595+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='KOH' AIRFLOW_CTX_TASK_ID='data_ml' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T17:55:20.000429+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T17:55:20.000429+00:00'
[2023-12-26T22:56:00.598+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-26T22:56:00.599+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/kda/ML_lab3/MLops_lab3/ && python /home/kda/ML_lab3/MLops_lab3/scripts/model_learn.py']
[2023-12-26T22:56:00.621+0500] {subprocess.py:86} INFO - Output:
[2023-12-26T22:56:08.167+0500] {subprocess.py:93} INFO - <class 'pandas.core.frame.DataFrame'>
[2023-12-26T22:56:08.167+0500] {subprocess.py:93} INFO - RangeIndex: 704 entries, 0 to 703
[2023-12-26T22:56:08.170+0500] {subprocess.py:93} INFO - Columns: 220 entries, Price (in USD) to i8
[2023-12-26T22:56:08.170+0500] {subprocess.py:93} INFO - dtypes: bool(212), float64(2), int64(6)
[2023-12-26T22:56:08.170+0500] {subprocess.py:93} INFO - memory usage: 189.9 KB
[2023-12-26T22:56:08.170+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-26T22:56:08.171+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/scripts/model_learn.py", line 36, in <module>
[2023-12-26T22:56:08.171+0500] {subprocess.py:93} INFO -     clf = DecisionTreeClassifier(**params)
[2023-12-26T22:56:08.171+0500] {subprocess.py:93} INFO - TypeError: DecisionTreeClassifier.__init__() got an unexpected keyword argument 'seed'
[2023-12-26T22:56:08.663+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-26T22:56:08.670+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-26T22:56:08.677+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=KOH, task_id=data_ml, execution_date=20231226T175520, start_date=20231226T175600, end_date=20231226T175608
[2023-12-26T22:56:08.758+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 63 for task data_ml (Bash command failed. The command returned a non-zero exit code 1.; 11595)
[2023-12-26T22:56:08.790+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-26T22:56:08.817+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
