[2023-12-30T17:50:07.971+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KOH.evaluate manual__2023-12-30T12:48:04.791132+00:00 [queued]>
[2023-12-30T17:50:07.976+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KOH.evaluate manual__2023-12-30T12:48:04.791132+00:00 [queued]>
[2023-12-30T17:50:07.976+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-30T17:50:08.000+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): evaluate> on 2023-12-30 12:48:04.791132+00:00
[2023-12-30T17:50:08.000+0500] {standard_task_runner.py:57} INFO - Started process 23328 to run task
[2023-12-30T17:50:08.008+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'KOH', 'evaluate', 'manual__2023-12-30T12:48:04.791132+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/text.py', '--cfg-path', '/tmp/tmp2we31qky']
[2023-12-30T17:50:08.009+0500] {standard_task_runner.py:85} INFO - Job 365: Subtask evaluate
[2023-12-30T17:50:08.040+0500] {task_command.py:416} INFO - Running <TaskInstance: KOH.evaluate manual__2023-12-30T12:48:04.791132+00:00 [running]> on host vm2.myguest.virtualbox.org
[2023-12-30T17:50:08.144+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='KOH' AIRFLOW_CTX_TASK_ID='evaluate' AIRFLOW_CTX_EXECUTION_DATE='2023-12-30T12:48:04.791132+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-30T12:48:04.791132+00:00'
[2023-12-30T17:50:08.145+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-30T17:50:08.146+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/kda/ML_lab3/MLops_lab3/ && python /home/kda/ML_lab3/MLops_lab3/scripts/evaluate.py']
[2023-12-30T17:50:08.169+0500] {subprocess.py:86} INFO - Output:
[2023-12-30T17:50:09.896+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-30T17:50:09.897+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/scripts/evaluate.py", line 13, in <module>
[2023-12-30T17:50:09.897+0500] {subprocess.py:93} INFO -     import infer_signature
[2023-12-30T17:50:09.898+0500] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'infer_signature'
[2023-12-30T17:50:10.193+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-30T17:50:10.202+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-30T17:50:10.205+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=KOH, task_id=evaluate, execution_date=20231230T124804, start_date=20231230T125007, end_date=20231230T125010
[2023-12-30T17:50:10.229+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 365 for task evaluate (Bash command failed. The command returned a non-zero exit code 1.; 23328)
[2023-12-30T17:50:10.270+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-30T17:50:10.285+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
